removed elm package install

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -103,30 +103,30 @@ download ${S3_URL}/elm/${ELM_VERSION} elm-make
 
 chmod -R a+x ${cache}/bin
 
-# Restore elm package cache
-if test -d ${cache}/elm-stuff; then
-   echo "-----> Restoring Elm cache"
-   cp -r ${cache}/elm-stuff ${build}/elm-stuff
-fi
-
-cd ${build}
-echo "-----> Fetching dependencies"
-elm package install --yes | indent
-
-get_app_json_env() {
-    name=$1
-    if ! test -f ${build}/app.json; then
-        error "app.json missing."
-    fi
-    python -c "import json; j=json.load(open('app.json')); print j['env']['${name}']"
-}
-
-ELM_COMPILE=$(get_app_json_env "ELM_COMPILE")
-echo "-----> Compiling with ${ELM_COMPILE}"
-${ELM_COMPILE} | indent
-
-# Copy package and compile artifacts back to cache
-cp -r ${build}/elm-stuff ${cache}/
+# # Restore elm package cache
+# if test -d ${cache}/elm-stuff; then
+#    echo "-----> Restoring Elm cache"
+#    cp -r ${cache}/elm-stuff ${build}/elm-stuff
+# fi
+# 
+# cd ${build}
+# echo "-----> Fetching dependencies"
+# elm package install --yes | indent
+# 
+# get_app_json_env() {
+#     name=$1
+#     if ! test -f ${build}/app.json; then
+#         error "app.json missing."
+#     fi
+#     python -c "import json; j=json.load(open('app.json')); print j['env']['${name}']"
+# }
+# 
+# ELM_COMPILE=$(get_app_json_env "ELM_COMPILE")
+# echo "-----> Compiling with ${ELM_COMPILE}"
+# ${ELM_COMPILE} | indent
+# 
+# # Copy package and compile artifacts back to cache
+# cp -r ${build}/elm-stuff ${cache}/
 
 ########## gmp #####################################################
 LIBGMP_VER=${LIBGMP_VER:-6.0.0a}
